name: Webhook to Mattermost 

on:
  push:
    branches:
      - main

jobs:
  post-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send hello world to Mattermost
        env:
          MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d '{"text":"Hello World"}' \
            "$MATTERMOST_WEBHOOK_URL"
